In [3]:
import numpy as np


a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)
c = np.random.rand(3)
d = [1,2,3]
print(c)
e = np.dot(c,d)
print(e)
tic = time.time()
f = np.dot(a,b)
toc = time.time()
print(f)
print('vetorized version\t' + str(1000*(toc-tic))+'ms')

g = 0 
tic = time.time()
for i in range(1000000):
    g += a[i]*b[i]
toc = time.time()
print(g)
print('loop version\t' + str(1000*(toc-tic))+'ms')




[0.92163118 0.69659857 0.33819332]
3.3294082749050395
249578.66253230738
vetorized version	0.9241104125976562ms
249578.6625323141
loop version	540.3602123260498ms


## What I find above

First *np.random.rand(N)* creates a N dimensional vector and *np.dot* menas dot product
###### and you can also find that

the loop version really slow than the vectorize version!


#### SIMD helps the function implement like np.dot() runs faster

Both under the GPU and CPU 

### So here is the note of the broadcating and the debug skii
first let we looking of the braodcating

In [6]:
A = np.array([[56.0,0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
Cal = A.sum(axis=0)
print(Cal)

[ 59.  239.  155.4  76.9]


In [9]:
percentage = A/Cal.reshape(1,4)
print(percentage)

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


So what we see above is that python brodcasting the (1,4) Cal Matrix to the (3,4) matrix same as the A 

Also the *axis=0* means vertical direction and the *axis=1* means the horizatal direction

### But the broadcasting may arise the error and bug,
#### Here is tips from angrew

In [10]:
a= np.random.randn(5)
print(a)

[-1.83088109  1.30006749  0.55872459  0.17494509  0.65157424]


In [11]:
print(a.shape)

(5,)


In [12]:
print(a.T)

[-1.83088109  1.30006749  0.55872459  0.17494509  0.65157424]


In [13]:
print(np.dot(a.T,a))

5.809629001411512


### _______seperate line______

So what happened above is that if we directly using the *(5)* we got the structure called*Rank 1 array* type in python, Under such structure we could find that the transpose of the a and a were exactly the same, So simply you could not got the out product of the a.T and a

## So we using the tips below

In [15]:
a = np. random.randn(5,1)
print(a)

[[-3.1971341 ]
 [ 0.58662197]
 [ 0.5608328 ]
 [ 1.41608014]
 [-0.3395458 ]]


In [16]:
print(a.T)

[[-3.1971341   0.58662197  0.5608328   1.41608014 -0.3395458 ]]


In [17]:
print(np.dot(a.T,a))
print(np.dot(a,a.T))

[[13.00089955]]
[[10.22166647 -1.87550911 -1.79305766 -4.52739811  1.08557345]
 [-1.87550911  0.34412534  0.32899684  0.83070373 -0.19918503]
 [-1.79305766  0.32899684  0.31453342  0.79418419 -0.19042842]
 [-4.52739811  0.83070373  0.79418419  2.00528297 -0.48082406]
 [ 1.08557345 -0.19918503 -0.19042842 -0.48082406  0.11529135]]


### So exactly,the problem we met above solved

In [20]:
assert(a.shape ==(5,1))
print(a)

[[-3.1971341 ]
 [ 0.58662197]
 [ 0.5608328 ]
 [ 1.41608014]
 [-0.3395458 ]]


### So in the programming do not using the Rank 1 array instead using the whole shape array of the matrix

### Try 

In [4]:
import numpy as np
a = np.random.randn(3,3)
b = np.random.randn(3,1)
print(a*b)


[[ 1.48039329 -0.68727756  0.44343401]
 [ 0.77933488  0.88867013 -2.46006448]
 [ 0.2233973   0.80149491 -0.03419342]]


##### a*b is element-wisable, np.dot()is matrix mutification