# Here is the note of the first Week
### Also check the slide I catch


### bias and Variance

- bias 偏差 (high error)
- Variance 方差 （overfitting)


## Basic recipe for ML 

- high bias?  ----> yes ---> 
- - bigger NN + Trianing longer+( other structure) 
- high variance?

"Bias variance tradeoff" 

## Regulazation

## try the basic dropout

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[2,3,4]])
print(a)

[[1 2 3]
 [2 3 4]]


In [3]:
x= a.shape[0]
y= a.shape[1]
keep_prob = 0.8
d3 =np.random.rand(a.shape[0],a.shape[1])<keep_prob #here is random determined the desliminate part exist broadcasting
a3 = np. multiply(a,d3)
print("the dimension of the a matrix is " +str(x)+"&"+str(y))
print(d3)
print(a3)

the dimension of the a matrix is 2&3
[[False  True False]
 [ True False  True]]
[[0 2 0]
 [2 0 4]]


### keep the expectation value of the a3 stay the same

In [12]:
c3 = a3/keep_prob#
print(c3)

[[0.  2.5 0. ]
 [2.5 0.  5. ]]


## Understanding Dropout

similar to L2 norm
So if worried about sone layer will overfitting, you can increas the key prob

#### pros and cons
- advantage: A good regulazation way, useful when you have small data sets: *the computer vision* as a example
- downside: no well defined *cost function J* So you are losing the way which plots J to debugging

#### Method to  solve this problem 
- first, turn off the *drop out*
- doing the nomal debugging *whether the J is decreasing for every iteration*
- finish it, than open the *drop out* to train

## Other Methods to do the regulazation
#### Date augmentation ---> fake trainning example
- flipping the images to double the data sets 
- random transation 
- - can avoid the overfitting
- ditorition adapt

#### Early Stopping --->stop ensure the mid-size omega
 

- plot the the trainning error (or the J)
- + plot the dev set error
- #advantage: using this method you can just doing one interation rather than find the hyperparameter(computationally expensive)

#### L2 Regulazation


*some conception called the orthognalization*

In [11]:
%%latex 
$x^2 \quad
\text{this is try the function of the Jupyter}$

<IPython.core.display.Latex object>

# Setting up your optimize problem
## Normalizing the trainning sets
- basic idea is that:

$$ \bar{x} = \frac{x-\mu}{\sigma}$$

- so advantage is the gradinet will be much fast



## vanishin / exploding gradients

assume that we had $\omega^{[l]}$

$$ \omega^{[l]} = \left[\begin{array}{l}
a & 0\\
0 & b
\end{array}\right]$$

if we had 

$$ \omega^{[l]} > I \text{ the gradients will be exploding}$$

$$ \omega^{[l]} < I \text{ the gradients will be vanishing}$$

they will exist will be clear when the network going deeper

## Weight Initialization for Deep Networks

- try to set the $ \omega$  to the 1 which help vanishing or exploding
- - and you check the detail in lecture

- single neuron example 

#### and some example for 

$$var(\omega:)$$

- for tanh ---> xavies innitialzation:  $\sqrt{\frac{1}{n^{[l-1]}}}$

- for Relu --->  $\sqrt{\frac{2}{n^{[l-1]}}}$
 
- some others --->   $\sqrt{\frac{2}{n^{[l-1]}+n^{[l]}}}$

## refine the backpropagation:
#### Numerical calculate the gradient(in Machine learning couse skip)

#### Gradient checking( skip)

- reshape into a giant vector
-  $10^{-7}$  therohold
 
#### some notes 

- dont use in training(slow) --only debug
- identify the bug
- remeber regularization
- of course doesn't work with dropout( back to the dropout part)
- run the gradient check can be both in the:
- - initial part
- - some step after interation

  <h4 style = 'color: orange'> the end of the week1 (temporate) </h4>

# So here is the note for week6 Machine Learning
##  Model selection problem
#### the data was seperated in 
- training data set
- cross valiadation set
- test set

#### Same problem for the bias and the variance *with different method to deal it*
- high bias(underfit)
- high variance (overfitting)

# hyper-parameter Tuning, Optimization

## Classification

### layers

### hidden units

### activation function

### learning rate

## data sets 

### Train

### Dev

- Usiing this part to select the algorithom

### test

## The Problem may cause

### Bias

- high

	- underfitted

- low

	- overfitted

### Variance

- high 

	- overfitted

- low

	- underfitted

### Problem Solving

- change the hyper-parameters

	- logistic Regression

		- L_1 + L_2 regularization
		- Dropout Regularization

			- Inverted Drop out:on the notion

				- On (training process)
				- Off( test process)

		- Early Stopping(on the slide1)

			- Watch the curves

- Optimize problem

	- Vanishing/ exploding Gradients)

		- Weight initialization 

			- let w ---> 1 

				- for tanh (xavis)
				- Relu
				- others

### Back Propagation accuracy checking 

- Gradient Checking

## Optimization MEthod

### Mini Batch Method

- chose the size
- ramdom position implement
- Gradient decent

### Exponentially Weighted average

- Bias correction

## Hyper-parameter choose

### Don't using grid

- using random values

### Coarse to Fine

### Properly scaling

### Two model to find Hyper

- panda
- cavia

### Normalizing speed up

- batch Norm

	- has slight Regularization effect

## multi-class Recognition

### SoftMax method

*XMind - Trial Version*